name: s3-deploy-sample
on:  push

jobs:
  UploadStaticFiles:
    name: Upload static files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload ZIP to S3
        uses: NotCoffee418/s3-zip-upload@v1.3
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: appstack-sourcebucketddd2130a-y9entrhekxqz
          AWS_REGION: ap-northeast-1
          SOURCE_MODE: ZIP
          SOURCE_PATH: ./
          DEST_FILE: artifacts.zip
